# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"

  redis:
    image: redis:latest
    ports:
      - "63790:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    env_file:
      - .env
